name = "jobs-api"
main = "src/index.js"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "ea080f698fdf34fa24a55dbd904ad90a"

[triggers]
crons = ["17 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "jobs"
database_id = "41c3449c-79fe-44ab-8505-fb4b8ed87724"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CONFIG"
id = "681a6bf437c14bdfbebcfaecb9910edd"
